{% set name = "fmtlib" %}
{% set version = "7.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fmtlib/fmt
  git_tag: {{ version }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - cmake

about:
  home: https://github.com/fmtlib/fmt
  summary: "{fmt} is an open-source formatting library providing a fast and safe alternative to C stdio and C++ iostreams."
  license: Custom
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - bkreider
